# Generated by Django 3.2.16 on 2022-10-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_auto_20221028_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_category_filter',
            field=models.CharField(choices=[('gaps', 'Gaps'), ('rails', 'Rail'), ('ledges', 'Ledges'), ('street', 'Street')], default='none', max_length=50),
        ),
    ]
