# Generated by Django 3.2.16 on 2022-10-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_alter_post_post_category_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_category_filter',
            field=models.CharField(choices=[('gaps', 'Gaps'), ('rails', 'Rail'), ('ledges', 'Ledges'), ('street', 'Street')], default='normal', max_length=50),
        ),
    ]
