# Generated by Django 3.2.16 on 2022-10-31 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0004_alter_post_post_category_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(default='../default_VID', null=True, upload_to='media'),
        ),
    ]
