# Generated by Django 3.2.16 on 2022-10-31 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0006_alter_post_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
    ]
