# Generated by Django 3.2.16 on 2022-10-31 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0007_remove_post_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='../default_profile_qdjgyp', null=True, upload_to='media'),
        ),
    ]
