# Generated by Django 3.2.16 on 2022-10-31 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0008_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
    ]
