# Generated by Django 3.2.16 on 2022-10-28 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='author',
            new_name='owner',
        ),
    ]
