# Generated by Django 3.2.16 on 2022-10-28 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_rename_author_profile_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='owner',
            new_name='author',
        ),
    ]
