# Generated by Django 3.2.16 on 2022-10-31 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postvideo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopost',
            name='video',
            field=models.FileField(null=True, upload_to='video/%y'),
        ),
    ]
