# Generated by Django 3.2.16 on 2022-10-31 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postvideo', '0003_remove_videopost_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='videopost',
            name='video',
            field=models.FileField(null=True, upload_to='media/'),
        ),
    ]
