# Generated by Django 3.2.16 on 2022-10-31 16:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postvideo', '0004_videopost_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopost',
            name='video',
            field=cloudinary.models.CloudinaryField(default='../default_VID', max_length=255),
        ),
    ]
