# Generated by Django 3.2.16 on 2022-10-31 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postvideo', '0005_alter_videopost_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videopost',
            name='video',
        ),
    ]
