# Generated by Django 3.2.16 on 2022-10-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postvideo', '0006_remove_videopost_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='videopost',
            name='video',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
    ]
